version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py

python:
   version: 3.11
   install:
      - method: pip
        path: .
        extra_requirements:
          - dev
      - requirements: docs/requirements.txt